version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ls -la
            pwd
            docker build --tag timeoff:latest .
            docker images

      #  - sonarcloud/scan
      - persist_to_workspace:
          root: /app
          paths:
            - .
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: check_files
          command: |
            ls -la
            ls -la
            pwd
  Prod:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: check_files_2
          command: |
            ls -la
            cd risk_pd_model
            ls -la
            pwd
workflows:
  main:
    jobs:
      - build

      - testing:
          requires:
            - build

      - Prod:
          requires:
            - testing
          filters:
            branches:
              only:
                - master