version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'
    working_directory: /home/circleci/project/risk_pd_model
    steps:
      - checkout
      - run:
          name: check_files
          command: |
            ls -la
            pwd
      #  - sonarcloud/scan
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: check_files
          command: |
            ls -la
            ls -la
            pwd
  Prod:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: check_files_2
          command: |
            ls -la
            cd risk_pd_model
            ls -la
            pwd
workflows:
  main:
    jobs:
      - build

      - testing:
          requires:
            - build

      - Prod:
          requires:
            - testing
          filters:
            branches:
              only:
                - master