#version: 2.1
#orbs:
#  aws-ecr: circleci/aws-ecr@6.15
#  aws-ecs: circleci/aws-ecs@2.0.0
#workflows:
#  build-and-deploy:
#    jobs:
#      - aws-ecr/build-and-push-image:
#          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com"
#          repo: "${AWS_RESOURCE_NAME_PREFIX}"
#          region: "us-east-1"
#          tag: "${CIRCLE_SHA1}"
#      - aws-ecs/deploy-service-update:
#          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
#          cluster-name: "cb-cluster"
#          aws-region: "us-east-1"
#          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app_node:${CIRCLE_SHA1}"
#          requires:
#            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
#

version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          cluster-name: 'cb-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
          family: "cb-app"
          requires:
            - aws-ecr/build-and-push-image